# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2f785ead0de4af2f980e42bc74e040a03966ae3f042ea9ff64e86a1576dfb8cdca8a1e6536d510fd07bd22657f467d13b0ac76081893b1d067c056b36ea56ad

test:
  secret_key_base: 8376c7205fb99a44fa22c70463fbebeae36a24cee7e3f84d4aa7a7bd39b602e6aa2541740b8f746285f03e4124a9f2551edca2cd90524b9d361019a6f44cb171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
